<html><head>
<!-- ViewCVS       -- http://viewcvs.sourceforge.net/
     by Greg Stein -- mailto:gstein@lyra.org
  -->

<title>dotmods/loc_chinese/locales/cn/common.inc - view - 1.2</title></head>
<body bgcolor="#eeeeee">
<table width="100&#37;" border=0 cellspacing=0 cellpadding=1 bgcolor="#9999ee">
<tr valign=bottom><td>
<a href="common.inc#rev1.2"><img src="/viewcvs/back.gif" alt="[BACK_ICON]" border=0 width=16 height=16></a>
<b>Return to <a href="common.inc#rev1.2">common.inc</a> CVS log</b> <img src="/viewcvs/text.gif" alt="[FILE_ICON]" border=0 width=16 height=16></td>
<td align=right><img src="/viewcvs/dir.gif" alt="[DIR_ICON]" border=0 width=16 height=16> <b>Up to <a href="http://sourceforge.net/">[SourceForge]</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/#dirlist">dotmods</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/#dirlist">loc_chinese</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/locales/#dirlist">locales</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/locales/cn/#dirlist">cn</a></b></td>
</tr></table>
<hr noshade>
<table width="100&#37;"><tr><td bgcolor="#ffffff">
File: <a href="http://sourceforge.net/">[SourceForge]</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/#dirlist">dotmods</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/#dirlist">loc_chinese</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/locales/#dirlist">locales</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/locales/cn/#dirlist">cn</a> / <a href="/cgi-bin/viewcvs.cgi/dotmods/loc_chinese/locales/cn/common.inc#dirlist">common.inc</a> </b>
(<a href="/cgi-bin/viewcvs.cgi/*checkout*/dotmods/loc_chinese/locales/cn/common.inc?rev=1.2"
 target="cvs_checkout"
 onClick="window.open('about:blank','cvs_checkout','resizeable=1,scrollbars=1 ');"
><b>download</b></a>)
<br>
Revision <b>1.2</b>
, <i>Mon Jan 20 01:33:53 2003 UTC</i> (26 hours, 33 minutes ago) by <i>atang</i>
<br>Branch: <b>MAIN</b>
<br>CVS Tags: <b>HEAD</b>
<br>Changes since <b>1.1: +86 -86 lines</b>
<pre>First commit
</pre>
</td></tr></table>
<hr noshade>
<pre>
##
## DO NOT MODIFY THIS FILE BY HAND!
##
"- New Item -"=&gt;"- 新建 -",
"About"=&gt;"关于",
"Active Projects"=&gt;"进行中项目",
"Add"=&gt;"添加",
"Address"=&gt;"地址",
"All"=&gt;"所有",
"Archived Projects"=&gt;"已完成项目",
"Birthday"=&gt;"生日",
"Calendar"=&gt;"日历",
"City"=&gt;"城市",
"Clients &amp; Companies"=&gt;"客户及公司",
"Companies"=&gt;"公司",
"Company"=&gt;"公司",
"Contact"=&gt;"联系人",
"Contacts"=&gt;"联系人",
"Country"=&gt;"国家",
"Current user"=&gt;"当前用户",
"Department"=&gt;"部门",
"Departments"=&gt;"部门",
"Description"=&gt;"概述",
"Details"=&gt;"详细资料",
"Edit"=&gt;"编辑",
"Email"=&gt;"电子邮件",
"Event"=&gt;"事项",
"Fax"=&gt;"传真",
"File"=&gt;"文件",
"Files"=&gt;"文件",
"First Name"=&gt;"名字",
"Forums"=&gt;"论坛",
"Help"=&gt;"帮助",
"Last Name"=&gt;"姓氏",
"Login Failed"=&gt;"登录失败",
"Logout"=&gt;"注销",
"Mobile Phone"=&gt;"移动电话",
"My"=&gt;"我的",
"My Info"=&gt;"个人资料",
"Name"=&gt;"名称",
"No"=&gt;"否",
"No data available"=&gt;"无数据可用",
"Not implemented"=&gt;"无法执行",
"Owner"=&gt;"主管",
"Password"=&gt;"密码",
"Phone"=&gt;"电话",
"Private Entry"=&gt;"私人条目",
"Project"=&gt;"项目",
"Projects"=&gt;"项目",
"Select"=&gt;"选择",
"Show"=&gt;"显示",
"State"=&gt;"省份",
"Summary"=&gt;"汇总",
"System Admin"=&gt;"系统管理",
"Task"=&gt;"任务",
"Tasks"=&gt;"任务",
"Tickets"=&gt;"问题跟踪",
"Title"=&gt;"标题",
"Type"=&gt;"特征",
"URL"=&gt;"网址",
"User Admin"=&gt;"用户管理",
"Username"=&gt;"用户名称",
"Users"=&gt;"用户",
"Yes"=&gt;"是",
"Zip"=&gt;"邮编",
"add"=&gt;"添加",
"back"=&gt;"返回",
"cancel"=&gt;"取消",
"clear"=&gt;"清除",
"delete"=&gt;"删除",
"either"=&gt;"任选一种(可切换)",
"flat"=&gt;"平铺模式",
"forgotPassword"=&gt;"求助! 我忘记用户名和密码了!",
"login"=&gt;"登录",
"new department"=&gt;"新建部门",
"next"=&gt;"往后",
"nodepartments"=&gt;"没有部门",
"openSource"=&gt;"开放源码项目管理应用程序",
"previous"=&gt;"往前",
"required"=&gt;"必填",
"requiredField"=&gt;"为必填",
"save"=&gt;"保存",
"search"=&gt;"搜索",
"sort by"=&gt;"排序",
"submit"=&gt;"提交",
"tabbed"=&gt;"标签模式",
"test"=&gt;"测试",
</pre>
<hr noshade><table width="100&#37;" border=0 cellpadding=0 cellspacing=0><tr>
<td align=left><address><a href="http://sourceforge.net/">Back to SourceForge</a></address></td>
<td align=right>Powered by<br><a href="http://viewcvs.sourceforge.net/">ViewCVS 0.8</a>
</td></tr></table>
</body></html>
